# Generated by Django 3.0.7 on 2020-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Автоматизированная Система')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('int_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('protocol', models.CharField(max_length=50, verbose_name='Протокол')),
                ('as_provider', models.CharField(max_length=50, verbose_name='АС Поставщик')),
                ('fp_provider', models.CharField(max_length=50, verbose_name='ФП Поставщик')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('iniciator', models.CharField(max_length=50, verbose_name='Инициатор')),
                ('int_technology', models.CharField(max_length=50, verbose_name='Технология взаимодействия')),
                ('consumer_status', models.CharField(max_length=50, verbose_name='Потребитель - Статус')),
                ('consumer_date', models.CharField(max_length=50, verbose_name='Потребитель - Срок')),
                ('consumer_as', models.CharField(max_length=50, verbose_name='Потребитель - АС')),
                ('consumer_role', models.CharField(max_length=50, verbose_name='Потребитель - Роль')),
                ('consumer_process', models.CharField(max_length=50, verbose_name='Потребитель - Процесс')),
                ('consumer_sla', models.CharField(max_length=50, verbose_name='Потребитель - SLA')),
                ('consumer_comment', models.CharField(max_length=50, verbose_name='Потребитель - Комментарий')),
                ('data_description', models.CharField(max_length=500, verbose_name='Передаваемые данные - Описание')),
                ('data_encoding', models.CharField(max_length=50, verbose_name='Передаваемые данные - Кодировка')),
                ('data_format', models.CharField(max_length=50, verbose_name='Передаваемые данные - Формат')),
                ('data_confidential_level', models.CharField(max_length=50, verbose_name='Передаваемые данные - Категория конфиденциальности')),
                ('data_integrity_level', models.CharField(max_length=50, verbose_name='Передаваемые данные - Категория целостности')),
                ('schedule_initiation', models.CharField(max_length=50, verbose_name='Регламент выгрузки - Инициация')),
                ('schedule_year', models.CharField(max_length=50, verbose_name='Регламент выгрузки - Год')),
                ('schedule_month', models.CharField(max_length=50, verbose_name='Регламент выгрузки - Месяц')),
                ('schedule_week', models.CharField(max_length=50, verbose_name='Регламент выгрузки - Неделя')),
                ('schedule_day', models.CharField(max_length=50, verbose_name='Регламент выгрузки - День')),
                ('schedule_load_profile', models.CharField(max_length=50, verbose_name='Регламент выгрузки - Характер нагрузки')),
                ('filesize_min', models.CharField(max_length=50, verbose_name='Размер файла - Мин')),
                ('filesize_max', models.CharField(max_length=50, verbose_name='Размер файла - Макс')),
                ('filesize_avg', models.CharField(max_length=50, verbose_name='Размер файла - Средний')),
                ('security_ssl_tls', models.CharField(max_length=50, verbose_name='Информационная безопасность - SSL/TLS')),
                ('security_encription', models.CharField(max_length=50, verbose_name='Информационная безопасность - Шифрование')),
                ('security_digital_signature', models.CharField(max_length=50, verbose_name='Информационная безопасность - ЭП')),
            ],
        ),
    ]
