# Generated by Django 3.0.7 on 2020-06-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_as', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='architecture_standard_complience',
            field=models.CharField(default=' ', max_length=100, verbose_name='Соответствие стандартам архитектуры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='int_comment',
            field=models.CharField(default=' ', max_length=500, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
