# Generated by Django 3.0.7 on 2020-07-03 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код АС')),
                ('name', models.CharField(max_length=100, verbose_name='Автоматизированная Система')),
                ('owner', models.CharField(blank=True, max_length=50, verbose_name='Владелец')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('cloud_ready', models.CharField(blank=True, max_length=50, verbose_name='Cloud Ready/Native\t')),
                ('platform_ready', models.CharField(blank=True, max_length=50, verbose_name='Platform Ready')),
                ('owner_block', models.CharField(blank=True, max_length=50, verbose_name='Владелец - Блок')),
                ('owner_tribe', models.CharField(blank=True, max_length=50, verbose_name='Владелец - Трайб')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='Полное имя АС')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Псевдоним АС')),
                ('short_description', models.CharField(blank=True, max_length=50, verbose_name='Краткое описание')),
                ('rsa_id', models.CharField(blank=True, max_length=50, verbose_name='ID в RSA')),
                ('service_desk_id', models.CharField(blank=True, max_length=50, verbose_name='ID в Service Desk')),
                ('guid', models.CharField(blank=True, max_length=50, verbose_name='GUID')),
                ('centralization_level', models.CharField(blank=True, max_length=50, verbose_name='Уровень централизации')),
                ('system_criticality', models.CharField(blank=True, max_length=50, verbose_name='Критичность системы')),
                ('target_status', models.CharField(blank=True, max_length=50, verbose_name='Целевой статус')),
                ('target_readiness', models.CharField(blank=True, max_length=50, verbose_name='Готовность целевого решения')),
                ('as_lider', models.CharField(blank=True, max_length=50, verbose_name='Лидер АС')),
                ('as_architect', models.CharField(blank=True, max_length=50, verbose_name='Архитектор АС')),
                ('architect_in_charge', models.CharField(blank=True, max_length=50, verbose_name='Курирующий архитектор')),
                ('editors', models.CharField(blank=True, max_length=50, verbose_name='Редакторы')),
                ('target_architecture_diagram', models.ImageField(blank=True, upload_to='target_architecture_diagrams', verbose_name='Диаграмма целевой архитектуры')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('int_type', models.CharField(blank=True, max_length=50, verbose_name='Тип')),
                ('protocol', models.CharField(blank=True, max_length=50, verbose_name='Протокол')),
                ('as_provider', models.CharField(blank=True, max_length=50, verbose_name='АС Поставщик')),
                ('fp_provider', models.CharField(blank=True, max_length=50, verbose_name='ФП Поставщик')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('iniciator', models.CharField(blank=True, max_length=50, verbose_name='Инициатор')),
                ('int_technology', models.CharField(blank=True, max_length=50, verbose_name='Технология взаимодействия')),
                ('consumer_status', models.CharField(blank=True, max_length=50, verbose_name='Потребитель - Статус')),
                ('consumer_date', models.CharField(blank=True, max_length=50, verbose_name='Потребитель - Срок')),
                ('consumer_as', models.CharField(blank=True, max_length=50, verbose_name='Потребитель - АС')),
                ('consumer_role', models.CharField(blank=True, max_length=50, verbose_name='Потребитель - Роль')),
                ('consumer_process', models.CharField(blank=True, max_length=50, verbose_name='Потребитель - Процесс')),
                ('consumer_sla', models.CharField(blank=True, max_length=50, verbose_name='Потребитель - SLA')),
                ('consumer_comment', models.CharField(blank=True, max_length=50, verbose_name='Потребитель - Комментарий')),
                ('data_description', models.CharField(blank=True, max_length=500, verbose_name='Передаваемые данные - Описание')),
                ('data_encoding', models.CharField(blank=True, max_length=50, verbose_name='Передаваемые данные - Кодировка')),
                ('data_format', models.CharField(blank=True, max_length=50, verbose_name='Передаваемые данные - Формат')),
                ('data_confidential_level', models.CharField(blank=True, max_length=50, verbose_name='Передаваемые данные - Категория конфиденциальности')),
                ('data_integrity_level', models.CharField(blank=True, max_length=50, verbose_name='Передаваемые данные - Категория целостности')),
                ('schedule_initiation', models.CharField(blank=True, max_length=50, verbose_name='Регламент выгрузки - Инициация')),
                ('schedule_year', models.CharField(blank=True, max_length=50, verbose_name='Регламент выгрузки - Год')),
                ('schedule_month', models.CharField(blank=True, max_length=50, verbose_name='Регламент выгрузки - Месяц')),
                ('schedule_week', models.CharField(blank=True, max_length=50, verbose_name='Регламент выгрузки - Неделя')),
                ('schedule_day', models.CharField(blank=True, max_length=50, verbose_name='Регламент выгрузки - День')),
                ('schedule_load_profile', models.CharField(blank=True, max_length=50, verbose_name='Регламент выгрузки - Характер нагрузки')),
                ('filesize_min', models.CharField(blank=True, max_length=50, verbose_name='Размер файла - Мин')),
                ('filesize_max', models.CharField(blank=True, max_length=50, verbose_name='Размер файла - Макс')),
                ('filesize_avg', models.CharField(blank=True, max_length=50, verbose_name='Размер файла - Средний')),
                ('security_ssl_tls', models.CharField(blank=True, max_length=50, verbose_name='Информационная безопасность - SSL/TLS')),
                ('security_encription', models.CharField(blank=True, max_length=50, verbose_name='Информационная безопасность - Шифрование')),
                ('security_digital_signature', models.CharField(blank=True, max_length=50, verbose_name='Информационная безопасность - ЭП')),
                ('architecture_standard_complience', models.CharField(blank=True, max_length=100, verbose_name='Соответствие стандартам архитектуры')),
                ('int_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('automated_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archas.AutomatedSystem')),
            ],
        ),
    ]
